/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as UsuariosIndexImport } from './routes/usuarios/index'
import { Route as UsuariosCreateImport } from './routes/usuarios/create'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsuariosIndexRoute = UsuariosIndexImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRoute,
} as any)

const UsuariosCreateRoute = UsuariosCreateImport.update({
  id: '/usuarios/create',
  path: '/usuarios/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/usuarios/create': {
      id: '/usuarios/create'
      path: '/usuarios/create'
      fullPath: '/usuarios/create'
      preLoaderRoute: typeof UsuariosCreateImport
      parentRoute: typeof rootRoute
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/usuarios/create': typeof UsuariosCreateRoute
  '/usuarios': typeof UsuariosIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/usuarios/create': typeof UsuariosCreateRoute
  '/usuarios': typeof UsuariosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/usuarios/create': typeof UsuariosCreateRoute
  '/usuarios/': typeof UsuariosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/usuarios/create' | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/usuarios/create' | '/usuarios'
  id: '__root__' | '/' | '/about' | '/usuarios/create' | '/usuarios/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  UsuariosCreateRoute: typeof UsuariosCreateRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsuariosCreateRoute: UsuariosCreateRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/usuarios/create",
        "/usuarios/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/usuarios/create": {
      "filePath": "usuarios/create.tsx"
    },
    "/usuarios/": {
      "filePath": "usuarios/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
